### ISSUE TITLE
Improve type safety in MovingBox.tsx

### ISSUE THREAD

**Issue by JeKachan** [clbagrat/movingbox#1]
Hi, I noticed that in MovingBox uses a lot bang `!` operator for disabling typescript complains. I can fix it, if you do not mind.

**Comment by clbagrat** [comment]
sure thing, but I'd like you to wait for a week, since i'm cooking a quite significant update

**Comment by clbagrat** [comment]
solved in #2 
thanks a lot!

**Comment by JeKachan** [comment]
Glad to be useful :)
